#!/usr/bin/env ruby


$LOAD_PATH.unshift( File.expand_path File.dirname( __FILE__ ) )

require "stats"


def transaction
  history = History.load( "history.db" )
  history.add run_build
  yield history.data
  history.save
end


transaction do | data |
  data.each_pair do | kind, samples |
    puts "#{ kind } #{ samples.sum } #{ samples.sumsq } #{ samples.min } #{ samples.max } #{ samples.sd } #{ samples.mean }"
  end
end
